# Generated by Django 3.1.6 on 2021-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
