# Generated by Django 3.1.6 on 2021-02-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
