# Generated by Django 3.1.6 on 2021-02-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0003_todoitem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
